version: "3.9"

services:
  server:
    build:
      context: ./server
    container_name: web-server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev

  client:
    build:
      context: ./client
    container_name: web-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    depends_on:
      - server