version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: web-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev

  frontend:
    build:
      context: ./frontend
    container_name: web-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    depends_on:
      - backend